# Generated by Django 4.1 on 2022-08-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AlterField(
            model_name='account',
            name='acc_number',
            field=models.CharField(db_column='AccountNumber', max_length=20, primary_key=True, serialize=False),
        ),
    ]
